language: "ko-KR"   # 한국어로 리뷰

early_access: false

reviews:
  profile: "chill"   # 부드럽고 빠른 리뷰
  request_changes_workflow: true  # 필요 시 자동 승인/변경 요청 처리
  high_level_summary: true        # 요약 리뷰 제공
  review_status: true             # 리뷰 상태 PR에 표시
  collapse_walkthrough: true      # 줄 단위 리뷰는 기본적으로 접음 (필요할 때만 확인)
  auto_review:
    enabled: true   # PR 생성 시 자동 리뷰
    drafts: false   # Draft PR은 리뷰하지 않음

chat:
  auto_reply: true  # 질문에 자동 응답